---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  image: ubuntu-upstart:14.04
  run_command: /sbin/init

provisioner:
  name: ansible_playbook
  roles_path: roles
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  extra_vars: {}

  require_ruby_for_busser: false
  require_chef_omnibus: false

  verifier:
    name: busser
    ruby_bindir: "/usr/bin"

  playbook: site.yml

platforms:
  - name: ubuntu-14.04

suites:
  - name: nginx
    provisioner:
      hosts: nginx-servers

  - name: haproxy
    provisioner:
      hosts: haproxy-servers
